library("twitteR")
source("keys.R")
source("coleta.R")
setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
tweets=searchTwitter(termos, lang='pt', n=100, retryOnRateLimit=1)
saveRDS(tweets,'tweets.rds')
