library(twitteR)
source("keys.R")
source("conf.R")
setup_twitter_oauth(consumer_key, consumer_secret, access_token, access_secret)
tweets=searchTwitter(termos, lang='en', n=1000, retryOnRateLimit=1)
saveRDS(tweets,arquivo)
